### ISSUE TITLE
Feature: exclude filter

### ISSUE THREAD

**Issue by slundi** [Beastwick18/nyaa#39]
Hello

I was wondering if we could add a filtering feature so we can mainly display animes we are following

In the config files we would have something like:
```toml
# When matched, listed expressions here would hide the result from search
[exclude]
sentences = ["bleach", "your forma"]
# regexes = [] # if regex support is also planed
case_insensitive = true
```

Maybe a keyboard shortcut (<kbd>e</kbd>) in the TUI to enable/disable exclude filter will be useful too.
